title: Ankan Putatunda
logo: assets/img/Passport Sized Photo-ankan.putatunda2015@gmail.com.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
